### ISSUE TITLE
Taxons path not showing view

### ISSUE THREAD

**Issue by chris-barklem** [solidusio/solidus#1177]
I have a base build, all gems are up to date (see gemfile below). The path: /t/taxonamy_name renders the "The page you were looking for doesn't exist." The path: /t/taxonamy_name/taxon also shows the same message.

In rake routes:
nested_taxons GET      /t/*id(.:format)    spree/taxons#show

Using postgres, environment development.

Gemfile:

```
source 'https://rubygems.org'

ruby '2.3.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
 # Image storage for heroku production
gem 'aws-sdk', '< 2.0'
gem 'kaminari'
gem 'kaminari-i18n'
gem 'bootstrap-kaminari-views'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'bootstrap-select-rails'

# gem 'datashift'
# gem 'datashift_spree'

gem 'solidus'
gem 'solidus_auth_devise'
gem 'solidus_i18n', '~> 1.0'
gem 'solidus_globalize', github: 'solidusio-contrib/solidus_globalize', branch: 'master'
# gem 'solidus_product_description_editor', '~> 1.0', '>= 1.0.1'
gem 'solidus_social', '~> 1.0'

gem 'puma'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :production do
  # Heroku helper
  gem 'rails_12factor'

end
```

**Comment by CBarklem** [comment]
Here is the console output:

```
Started GET "/t/type-of-tea/white" for ::1 at 2016-05-22 11:47:15 +0200
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by Spree::TaxonsController#show as HTML
  Parameters: {"id"=>"type-of-tea/white"}
  Spree::User Load (1.0ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."id" = $1  ORDER BY "spree_users"."id" ASC LIMIT 1  [["id", 1]]
  Spree::Store Load (1.0ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."code" = $1 LIMIT 1  [["code", "localhost"]]
  Spree::Store Load (0.8ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE (url like '%localhost%')  ORDER BY "spree_stores"."id" ASC LIMIT 1
  Spree::Store Load (0.3ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."default" = $1  ORDER BY "spree_stores"."id" ASC LIMIT 1  [["default", "t"]]
  Spree::Order Load (1.3ms)  SELECT  "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."completed_at" IS NULL AND "spree_orders"."currency" = $1 AND "spree_orders"."guest_token" = $2 AND "spree_orders"."store_id" = $3 AND "spree_orders"."user_id" = $4 LIMIT 1  [["currency", "EUR"], ["guest_token", "2rKUauYcYhXsO6hPSpCN9w"], ["store_id", 1], ["user_id", 1]]
  Spree::Order Load (1.1ms)  SELECT  "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."user_id" = $1 AND "spree_orders"."frontend_viewable" = $2 AND "spree_orders"."store_id" = 1  ORDER BY "spree_orders"."created_at" DESC LIMIT 1  [["user_id", 1], ["frontend_viewable", "t"]]
  Spree::Taxon Load (1.9ms)  SELECT  "spree_taxons".* FROM "spree_taxons" INNER JOIN "spree_taxon_translations" ON "spree_taxon_translations"."spree_taxon_id" = "spree_taxons"."id" WHERE "spree_taxon_translations"."permalink" = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
' AND "spree_taxon_translations"."locale" IN ('en', 'es', 'ca') LIMIT 1
  Rendered public/404.html (2.2ms)
Completed 404 Not Found in 384ms (Views: 262.9ms | ActiveRecord: 21.7ms)
```

**Comment by jasonfb** [comment]
what happens if you open the rails console and do
```
Spree::Taxon.find_by_permalink!("type-of-tea/white")
```

Do you get the taxon your are looking for or do you get not found?

If you don't get the taxon, make sure the taxon you are thinking you should be loading has a permalink of "type-of-tea/white"

if you do get that taxon, go into the Solidus source code and debug directly inside of the ```show``` method, stepping through it line-by-line until you can determine what it is doing and why it is rendering your 404

**Comment by CBarklem** [comment]
I took a look:

```
| => rails console
Spree::Taxon.find_by_permalink!("type-of-tea/white")
Running via Spring preloader in process 1492
Loading development environment (Rails 4.2.6)
irb(main):001:0> Spree::Taxon.find_by_permalink!("type-of-tea/white")
  Spree::Taxon Load (1.5ms)  SELECT  "spree_taxons".* FROM "spree_taxons" INNER JOIN "spree_taxon_translations" ON "spree_taxon_translations"."spree_taxon_id" = "spree_taxons"."id" WHERE "spree_taxon_translations"."permalink" = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
' AND "spree_taxon_translations"."locale" = $1 LIMIT 1  [["locale", "en"]]
ActiveRecord::RecordNotFound: Couldn't find Spree::Taxon
```

I will did deeper.

**Comment by jasonfb** [comment]
hmm... it looks likes you don't have ```type-of-tea/white``` set as the permalink for a taxon ?

**Comment by CBarklem** [comment]
You would think that from the message. But the path is set for all three languages. Maybe its i18n related, globalize or similar.

**Comment by jasonfb** [comment]
it seems odd to me that it says 
```
"spree_taxon_translations"."permalink" = '--- !ruby/object:ActiveRecord::StatementCache::Substitute
```
unless I'm reading wrong is a cache object being passed in some kind of inspected way to the SQL query?

**Comment by jhawthorn** [comment]
@CBarklem I believe you're experiencing globalize/globalize#423. Could you try using the master version of globalize, where that should be fixed?

**Comment by CBarklem** [comment]
gem 'solidus_globalize', github: 'solidusio-contrib/solidus_globalize', branch: 'master' still not fixed.

**Comment by jhawthorn** [comment]
@CBarklem Could you try

```
gem 'globalize', github: 'globalize/globalize'
```

**Comment by jhawthorn** [comment]
Closing because I believe this is an issue in `globalize` itself (not solidus_globalize) which has been fixed in their master. If this isn't the case, please open a new issue against solidus_globalize.
