### ISSUE TITLE
Problem with billing_integration.rb

### ISSUE THREAD

**Issue by sviechnikov** [solidusio/solidus#1268]
Hi everyone.
Currently Solidus using activemerchant 1.48.0 and it is no really good, because in 
```core/app/models/spree/billing_integration.rb:10```, method ```ActiveMerchant::Billing::Base.integration_mode=``` missing OFFSITE_PAYMENT_EXTRACTION_MESSAGE constant, what every times makes error:

uninitialized constant ActiveMerchant::Billing::Base::OFFSITE_PAYMENT_EXTRACTION_MESSAGE

Can we update activemerchant to latest?

**Comment by sviechnikov** [comment]
In 1.49.0 it was fixed ...

**Comment by mamhoff** [comment]
You can update the `active_merchant` gem in your local app. Solidus just specifies a minimum version, it's not fixed. 
```ruby
# Gemfile
gem `active_merchant`, '~> 1.49.0'

**Comment by sviechnikov** [comment]
I have this messages:

The bundle currently has activemerchant locked at 1.48.0.

Bundler could not find compatible versions for gem "activemerchant":
  In Gemfile:
    solidus (>= 0) ruby depends on
      solidus_sample (= 1.2.2) ruby depends on
        solidus_core (= 1.2.2) ruby depends on
          activemerchant (~> 1.48.0) ruby

**Comment by tvdeyen** [comment]
@sviechnikov please try:

```
bundle update --source solidus_core
```

since `solidus` is just a "meta" gem

**Comment by sviechnikov** [comment]
I have the same message ... 

"The specifier ~> has a special meaning, best shown by example. ~> 2.0.3 is identical to >= 2.0.3 and < 2.1. ~> 2.1 is identical to >= 2.1 and < 3.0. ~> 2.2.beta will match prerelease versions like 2.2.beta.12"

I found this on http://bundler.io/gemfile.html

**Comment by sviechnikov** [comment]
It means, activemerchant can be updated in rage: from 1.48.0 to 1.48.9

**Comment by mamhoff** [comment]
@sviechnikov That requirement has been relaxed in master and the recently released version 1.3. Is it feasible for you to upgrade?

**Comment by sviechnikov** [comment]
@mamhoff, it is trouble for me, because my project will be released very soon and I have many dependencies with 1.2.2 version. I'm really glad about new 1.3.0 and will use it in feature projects. 

Maybe Solidus team can make little branch with possibility to upgrade activemerchant?
If it can be ...

**Comment by jhawthorn** [comment]
@sviechnikov We try very hard not to make such major changes to old versions. I know that the activemerchant bump was the source of some issues for our 1.3 adopters, and I don't want to surprise 1.2.x users with that on a future patch version upgrade.

If you need this, I recommend making your own fork and applying adde7d7d33e3a7d860887eafcc6d96420fca8d36 to the v1.2 branch.
